# Generated by Django 5.0.2 on 2024-04-04 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userhealth',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('goals', models.TextField(null=True)),
            ],
        ),
    ]
