# Generated by Django 5.0.2 on 2024-04-24 02:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('meal_type', models.CharField(choices=[(' ', ' '), ('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default=' ', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('fell_asleep_approx', models.TimeField()),
                ('woke_up_at', models.TimeField()),
                ('total_sleep_duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=200)),
                ('sleep_quality', models.CharField(choices=[(' ', ' '), ('exhausted', 'Exhausted'), ('tired', 'Tired'), ('groggy', 'Groggy'), ('rested', 'Rested'), ('energized', 'Energized')], default=' ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserHealthInfo',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('goals', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('miles', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('kilometers', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rest_periods', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, max_length=200)),
                ('rating', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='easy', max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
