# Generated by Django 5.0.2 on 2024-04-24 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0003_goals_nutrition_sleep_userhealthinfo_workoutentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
