# Generated by Django 5.0.2 on 2024-04-18 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0003_goals_foodentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthInfo',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('goals', models.TextField(null=True)),
            ],
        ),
    ]
