# Generated by Django 5.0.2 on 2024-04-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0004_userhealthinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Userhealth',
        ),
    ]
