# Generated by Django 5.0.2 on 2024-04-24 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0004_nutrition_user_delete_userhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='user',
            field=models.ForeignKey(default=12313, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
