# Generated by Django 5.0.2 on 2024-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0005_sleep_user_delete_userhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutentry',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
    ]
