# Generated by Django 5.0.2 on 2024-04-18 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0005_workout_delete_userhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='workout',
            name='kilometers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workout',
            name='miles',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workout',
            name='rating',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='rest_periods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=0),
        ),
    ]
