# Generated by Django 5.0.2 on 2024-04-18 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0006_workout_duration_workout_kilometers_workout_miles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('fell_asleep_approx', models.TimeField()),
                ('woke_up_at', models.TimeField()),
                ('total_sleep_duration', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('notes', models.TextField(blank=True, max_length=200)),
                ('sleep_quality', models.CharField(choices=[('exhausted', 'Exhausted'), ('tired', 'Tired'), ('groggy', 'Groggy'), ('rested', 'Rested'), ('energized', 'Energized')], default='', max_length=30)),
            ],
        ),
    ]
