# Generated by Django 5.0.2 on 2024-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0007_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='total_sleep_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
