# Generated by Django 5.0.2 on 2024-04-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0009_food_remove_foodentry_user_delete_goals_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='FoodEntry',
        ),
    ]
